// how to infer types automatically from typescript
// type TContributor = (typeof contributors)[number]

import { Contributors } from "./columns";

export const contributors: Contributors[] = [
  {
    id: 1,
    first_name: "Frasquito",
    last_name: "Jean",
    email: "fjean0@blinklist.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 39,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-04-03T02:15:47Z",
  },
  {
    id: 2,
    first_name: "Friedrich",
    last_name: "Ruthen",
    email: "fruthen1@google.com.au",
    gender: "Male",
    dependent: true,
    contributionAmount: 77,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-04-05T09:04:10Z",
  },
  {
    id: 3,
    first_name: "Birdie",
    last_name: "Grimme",
    email: "bgrimme2@auda.org.au",
    gender: "Female",
    dependent: false,
    contributionAmount: 71,
    contributionMethod: "Cash",
    dateJoined: "2023-09-28T21:05:56Z",
  },
  {
    id: 4,
    first_name: "Edi",
    last_name: "Tailour",
    email: "etailour3@naver.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 9,
    contributionMethod: "Online Payment",
    dateJoined: "2023-09-17T00:48:14Z",
  },
  {
    id: 5,
    first_name: "Harbert",
    last_name: "aManger",
    email: "hamanger4@cam.ac.uk",
    gender: "Male",
    dependent: true,
    contributionAmount: 34,
    contributionMethod: "Check",
    dateJoined: "2024-02-24T06:35:14Z",
  },
  {
    id: 6,
    first_name: "Cinnamon",
    last_name: "Lievesley",
    email: "clievesley5@51.la",
    gender: "Female",
    dependent: true,
    contributionAmount: 60,
    contributionMethod: "Credit Card",
    dateJoined: "2024-04-15T09:21:54Z",
  },
  {
    id: 7,
    first_name: "Theodor",
    last_name: "Skullet",
    email: "tskullet6@topsy.com",
    gender: "Male",
    dependent: false,
    contributionAmount: 52,
    contributionMethod: "Cash",
    dateJoined: "2024-05-19T10:56:10Z",
  },
  {
    id: 8,
    first_name: "Jarrad",
    last_name: "Clashe",
    email: "jclashe7@cmu.edu",
    gender: "Male",
    dependent: true,
    contributionAmount: 90,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-05-30T02:39:55Z",
  },
  {
    id: 9,
    first_name: "Vivia",
    last_name: "Pomery",
    email: "vpomery8@blogger.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 35,
    contributionMethod: "Check",
    dateJoined: "2024-02-12T12:26:40Z",
  },
  {
    id: 10,
    first_name: "Kaela",
    last_name: "Johnsson",
    email: "kjohnsson9@ow.ly",
    gender: "Female",
    dependent: true,
    contributionAmount: 68,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-04-18T19:20:31Z",
  },
  {
    id: 11,
    first_name: "Erskine",
    last_name: "Gillinghams",
    email: "egillinghamsa@uiuc.edu",
    gender: "Genderfluid",
    dependent: true,
    contributionAmount: 3,
    contributionMethod: "Cash",
    dateJoined: "2023-10-16T12:23:09Z",
  },
  {
    id: 12,
    first_name: "Amelina",
    last_name: "Overbury",
    email: "aoverburyb@skyrock.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 78,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-06-05T20:36:05Z",
  },
  {
    id: 13,
    first_name: "Darin",
    last_name: "Janaszkiewicz",
    email: "djanaszkiewiczc@blogger.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 91,
    contributionMethod: "Cash",
    dateJoined: "2024-05-26T18:10:00Z",
  },
  {
    id: 14,
    first_name: "Ashlan",
    last_name: "Thickins",
    email: "athickinsd@mayoclinic.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 60,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-09-30T12:32:01Z",
  },
  {
    id: 15,
    first_name: "Stewart",
    last_name: "Arkcoll",
    email: "sarkcolle@t-online.de",
    gender: "Genderqueer",
    dependent: true,
    contributionAmount: 26,
    contributionMethod: "Cash",
    dateJoined: "2024-02-17T19:05:45Z",
  },
  {
    id: 16,
    first_name: "Missie",
    last_name: "Varndell",
    email: "mvarndellf@addthis.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 28,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-12-02T13:25:03Z",
  },
  {
    id: 17,
    first_name: "Inesita",
    last_name: "Strick",
    email: "istrickg@princeton.edu",
    gender: "Female",
    dependent: false,
    contributionAmount: 70,
    contributionMethod: "Credit Card",
    dateJoined: "2023-10-10T05:34:23Z",
  },
  {
    id: 18,
    first_name: "Tory",
    last_name: "Peris",
    email: "tperish@pinterest.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 91,
    contributionMethod: "Cash",
    dateJoined: "2023-12-18T17:50:53Z",
  },
  {
    id: 19,
    first_name: "Pennie",
    last_name: "Rosson",
    email: "prossoni@usatoday.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 27,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-05-28T23:46:19Z",
  },
  {
    id: 20,
    first_name: "Barbara-anne",
    last_name: "Ruzicka",
    email: "bruzickaj@house.gov",
    gender: "Female",
    dependent: false,
    contributionAmount: 8,
    contributionMethod: "Check",
    dateJoined: "2023-12-08T06:03:19Z",
  },
  {
    id: 21,
    first_name: "Laraine",
    last_name: "Bellelli",
    email: "lbellellik@gmpg.org",
    gender: "Female",
    dependent: false,
    contributionAmount: 67,
    contributionMethod: "Check",
    dateJoined: "2023-12-21T04:58:13Z",
  },
  {
    id: 22,
    first_name: "Claudianus",
    last_name: "Elloit",
    email: "celloitl@sciencedirect.com",
    gender: "Male",
    dependent: false,
    contributionAmount: 24,
    contributionMethod: "Cash",
    dateJoined: "2023-08-11T22:47:26Z",
  },
  {
    id: 23,
    first_name: "Jonas",
    last_name: "Carabet",
    email: "jcarabetm@telegraph.co.uk",
    gender: "Male",
    dependent: false,
    contributionAmount: 81,
    contributionMethod: "Check",
    dateJoined: "2024-06-08T04:29:37Z",
  },
  {
    id: 24,
    first_name: "Perle",
    last_name: "Emeny",
    email: "pemenyn@intel.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 97,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-04-02T16:34:07Z",
  },
  {
    id: 25,
    first_name: "Beitris",
    last_name: "Forrester",
    email: "bforrestero@cdc.gov",
    gender: "Genderfluid",
    dependent: true,
    contributionAmount: 73,
    contributionMethod: "Online Payment",
    dateJoined: "2023-09-20T19:45:54Z",
  },
  {
    id: 26,
    first_name: "Norman",
    last_name: "Thiese",
    email: "nthiesep@toplist.cz",
    gender: "Male",
    dependent: true,
    contributionAmount: 93,
    contributionMethod: "Cash",
    dateJoined: "2023-12-21T07:03:21Z",
  },
  {
    id: 27,
    first_name: "Bailey",
    last_name: "Creenan",
    email: "bcreenanq@prweb.com",
    gender: "Male",
    dependent: false,
    contributionAmount: 55,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-07-24T01:20:51Z",
  },
  {
    id: 28,
    first_name: "Theda",
    last_name: "Tinson",
    email: "ttinsonr@cyberchimps.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 72,
    contributionMethod: "Check",
    dateJoined: "2024-05-14T06:29:44Z",
  },
  {
    id: 29,
    first_name: "Dennie",
    last_name: "MacAllaster",
    email: "dmacallasters@google.it",
    gender: "Genderfluid",
    dependent: true,
    contributionAmount: 89,
    contributionMethod: "Credit Card",
    dateJoined: "2023-07-18T04:20:29Z",
  },
  {
    id: 30,
    first_name: "Anatol",
    last_name: "Bonehill",
    email: "abonehillt@thetimes.co.uk",
    gender: "Male",
    dependent: true,
    contributionAmount: 94,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-08-10T19:21:43Z",
  },
  {
    id: 31,
    first_name: "Griswold",
    last_name: "Veivers",
    email: "gveiversu@storify.com",
    gender: "Male",
    dependent: false,
    contributionAmount: 99,
    contributionMethod: "Check",
    dateJoined: "2024-03-20T14:20:39Z",
  },
  {
    id: 32,
    first_name: "Tedd",
    last_name: "Tranfield",
    email: "ttranfieldv@squidoo.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 36,
    contributionMethod: "Cash",
    dateJoined: "2023-09-16T13:40:06Z",
  },
  {
    id: 33,
    first_name: "Pate",
    last_name: "Robertelli",
    email: "probertelliw@blogspot.com",
    gender: "Polygender",
    dependent: false,
    contributionAmount: 60,
    contributionMethod: "Check",
    dateJoined: "2023-11-07T04:49:35Z",
  },
  {
    id: 34,
    first_name: "Maegan",
    last_name: "Hallam",
    email: "mhallamx@csmonitor.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 34,
    contributionMethod: "Check",
    dateJoined: "2023-10-14T11:37:13Z",
  },
  {
    id: 35,
    first_name: "Rebeka",
    last_name: "Pembry",
    email: "rpembryy@elegantthemes.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 52,
    contributionMethod: "Check",
    dateJoined: "2024-01-09T13:12:32Z",
  },
  {
    id: 36,
    first_name: "Ricca",
    last_name: "Musk",
    email: "rmuskz@forbes.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 72,
    contributionMethod: "Check",
    dateJoined: "2023-09-12T23:15:15Z",
  },
  {
    id: 37,
    first_name: "Israel",
    last_name: "Kaplan",
    email: "ikaplan10@ft.com",
    gender: "Male",
    dependent: false,
    contributionAmount: 27,
    contributionMethod: "Online Payment",
    dateJoined: "2024-02-07T23:03:04Z",
  },
  {
    id: 38,
    first_name: "Gabriele",
    last_name: "Fero",
    email: "gfero11@disqus.com",
    gender: "Male",
    dependent: false,
    contributionAmount: 89,
    contributionMethod: "Online Payment",
    dateJoined: "2024-02-04T20:51:52Z",
  },
  {
    id: 39,
    first_name: "Estella",
    last_name: "Sicha",
    email: "esicha12@apple.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 85,
    contributionMethod: "Cash",
    dateJoined: "2023-10-23T09:41:38Z",
  },
  {
    id: 40,
    first_name: "Chantal",
    last_name: "Neiland",
    email: "cneiland13@blinklist.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 40,
    contributionMethod: "Check",
    dateJoined: "2023-12-07T23:03:15Z",
  },
  {
    id: 41,
    first_name: "Reinold",
    last_name: "McOmish",
    email: "rmcomish14@multiply.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 46,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-02-07T15:19:24Z",
  },
  {
    id: 42,
    first_name: "Frazier",
    last_name: "Evens",
    email: "fevens15@utexas.edu",
    gender: "Male",
    dependent: true,
    contributionAmount: 34,
    contributionMethod: "Check",
    dateJoined: "2024-03-31T04:34:31Z",
  },
  {
    id: 43,
    first_name: "Job",
    last_name: "Fabbro",
    email: "jfabbro16@unicef.org",
    gender: "Agender",
    dependent: false,
    contributionAmount: 37,
    contributionMethod: "Online Payment",
    dateJoined: "2024-04-28T10:39:23Z",
  },
  {
    id: 44,
    first_name: "Jessica",
    last_name: "Rakes",
    email: "jrakes17@storify.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 65,
    contributionMethod: "Cash",
    dateJoined: "2024-04-15T18:45:09Z",
  },
  {
    id: 45,
    first_name: "Pierette",
    last_name: "Chinge",
    email: "pchinge18@infoseek.co.jp",
    gender: "Female",
    dependent: false,
    contributionAmount: 29,
    contributionMethod: "Cash",
    dateJoined: "2024-01-21T21:29:07Z",
  },
  {
    id: 46,
    first_name: "Niall",
    last_name: "Neljes",
    email: "nneljes19@g.co",
    gender: "Male",
    dependent: false,
    contributionAmount: 89,
    contributionMethod: "Check",
    dateJoined: "2023-08-01T03:04:12Z",
  },
  {
    id: 47,
    first_name: "Tarrah",
    last_name: "Shank",
    email: "tshank1a@psu.edu",
    gender: "Female",
    dependent: false,
    contributionAmount: 89,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-12-03T07:09:59Z",
  },
  {
    id: 48,
    first_name: "Chilton",
    last_name: "Lambarton",
    email: "clambarton1b@tiny.cc",
    gender: "Agender",
    dependent: true,
    contributionAmount: 13,
    contributionMethod: "Check",
    dateJoined: "2024-03-11T04:25:06Z",
  },
  {
    id: 49,
    first_name: "Todd",
    last_name: "Hehnke",
    email: "thehnke1c@nydailynews.com",
    gender: "Male",
    dependent: false,
    contributionAmount: 25,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-03-26T03:09:15Z",
  },
  {
    id: 50,
    first_name: "Darla",
    last_name: "Linkin",
    email: "dlinkin1d@imageshack.us",
    gender: "Female",
    dependent: false,
    contributionAmount: 60,
    contributionMethod: "Credit Card",
    dateJoined: "2023-08-02T02:16:43Z",
  },
  {
    id: 51,
    first_name: "Thornton",
    last_name: "Van Der Straaten",
    email: "tvanderstraaten1e@multiply.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 4,
    contributionMethod: "Cash",
    dateJoined: "2024-06-15T05:33:12Z",
  },
  {
    id: 52,
    first_name: "Aileen",
    last_name: "Goolden",
    email: "agoolden1f@sitemeter.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 52,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-04-21T03:02:51Z",
  },
  {
    id: 53,
    first_name: "Carita",
    last_name: "Peasegod",
    email: "cpeasegod1g@printfriendly.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 23,
    contributionMethod: "Credit Card",
    dateJoined: "2023-10-11T21:14:45Z",
  },
  {
    id: 54,
    first_name: "Salli",
    last_name: "Gorch",
    email: "sgorch1h@army.mil",
    gender: "Female",
    dependent: true,
    contributionAmount: 67,
    contributionMethod: "Online Payment",
    dateJoined: "2024-03-08T03:00:34Z",
  },
  {
    id: 55,
    first_name: "Nigel",
    last_name: "Byng",
    email: "nbyng1i@mysql.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 91,
    contributionMethod: "Credit Card",
    dateJoined: "2024-06-20T17:16:44Z",
  },
  {
    id: 56,
    first_name: "Ardisj",
    last_name: "Mollen",
    email: "amollen1j@seattletimes.com",
    gender: "Non-binary",
    dependent: false,
    contributionAmount: 84,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-08-19T05:00:03Z",
  },
  {
    id: 57,
    first_name: "Hillyer",
    last_name: "Zelland",
    email: "hzelland1k@gravatar.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 6,
    contributionMethod: "Cash",
    dateJoined: "2024-03-03T16:41:46Z",
  },
  {
    id: 58,
    first_name: "Pablo",
    last_name: "Benediktovich",
    email: "pbenediktovich1l@wikia.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 47,
    contributionMethod: "Credit Card",
    dateJoined: "2023-10-15T03:18:53Z",
  },
  {
    id: 59,
    first_name: "Marion",
    last_name: "McReath",
    email: "mmcreath1m@hugedomains.com",
    gender: "Male",
    dependent: false,
    contributionAmount: 13,
    contributionMethod: "Online Payment",
    dateJoined: "2023-08-14T21:20:47Z",
  },
  {
    id: 60,
    first_name: "Shelbi",
    last_name: "Pfertner",
    email: "spfertner1n@topsy.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 1,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-02-22T02:31:16Z",
  },
  {
    id: 61,
    first_name: "Redd",
    last_name: "Elleton",
    email: "relleton1o@kickstarter.com",
    gender: "Male",
    dependent: false,
    contributionAmount: 14,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-07-16T18:40:19Z",
  },
  {
    id: 62,
    first_name: "Morissa",
    last_name: "Abbis",
    email: "mabbis1p@oakley.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 34,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-02-04T00:32:14Z",
  },
  {
    id: 63,
    first_name: "Bree",
    last_name: "Kilgallon",
    email: "bkilgallon1q@tinyurl.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 14,
    contributionMethod: "Credit Card",
    dateJoined: "2023-07-11T03:48:11Z",
  },
  {
    id: 64,
    first_name: "Jolie",
    last_name: "Annis",
    email: "jannis1r@edublogs.org",
    gender: "Female",
    dependent: true,
    contributionAmount: 6,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-07-30T03:33:30Z",
  },
  {
    id: 65,
    first_name: "Jorge",
    last_name: "Louth",
    email: "jlouth1s@people.com.cn",
    gender: "Male",
    dependent: true,
    contributionAmount: 1,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-04-19T20:13:37Z",
  },
  {
    id: 66,
    first_name: "Linn",
    last_name: "Palmer",
    email: "lpalmer1t@webnode.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 56,
    contributionMethod: "Check",
    dateJoined: "2023-08-06T08:30:04Z",
  },
  {
    id: 67,
    first_name: "Codie",
    last_name: "Lempenny",
    email: "clempenny1u@youtu.be",
    gender: "Female",
    dependent: false,
    contributionAmount: 80,
    contributionMethod: "Credit Card",
    dateJoined: "2024-02-05T00:34:53Z",
  },
  {
    id: 68,
    first_name: "Elizabeth",
    last_name: "Cleaton",
    email: "ecleaton1v@ihg.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 25,
    contributionMethod: "Check",
    dateJoined: "2023-10-13T02:33:02Z",
  },
  {
    id: 69,
    first_name: "Melissa",
    last_name: "Broadwood",
    email: "mbroadwood1w@blogtalkradio.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 82,
    contributionMethod: "Credit Card",
    dateJoined: "2023-07-03T11:21:18Z",
  },
  {
    id: 70,
    first_name: "Laurent",
    last_name: "Petroff",
    email: "lpetroff1x@dmoz.org",
    gender: "Male",
    dependent: false,
    contributionAmount: 92,
    contributionMethod: "Cash",
    dateJoined: "2024-04-08T06:47:53Z",
  },
  {
    id: 71,
    first_name: "Wylie",
    last_name: "Lies",
    email: "wlies1y@icq.com",
    gender: "Male",
    dependent: false,
    contributionAmount: 1,
    contributionMethod: "Online Payment",
    dateJoined: "2024-01-24T08:21:37Z",
  },
  {
    id: 72,
    first_name: "Caitrin",
    last_name: "Uzelli",
    email: "cuzelli1z@cafepress.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 83,
    contributionMethod: "Check",
    dateJoined: "2024-03-31T01:38:29Z",
  },
  {
    id: 73,
    first_name: "Zora",
    last_name: "Mogey",
    email: "zmogey20@reuters.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 89,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-10-18T17:12:11Z",
  },
  {
    id: 74,
    first_name: "Byran",
    last_name: "McCutcheon",
    email: "bmccutcheon21@wiley.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 46,
    contributionMethod: "Credit Card",
    dateJoined: "2024-04-20T08:14:40Z",
  },
  {
    id: 75,
    first_name: "Dix",
    last_name: "Ferrieroi",
    email: "dferrieroi22@hexun.com",
    gender: "Bigender",
    dependent: false,
    contributionAmount: 51,
    contributionMethod: "Cash",
    dateJoined: "2023-12-02T11:13:05Z",
  },
  {
    id: 76,
    first_name: "Frederick",
    last_name: "McGlade",
    email: "fmcglade23@intel.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 20,
    contributionMethod: "Credit Card",
    dateJoined: "2023-09-05T18:34:25Z",
  },
  {
    id: 77,
    first_name: "Babita",
    last_name: "Starkey",
    email: "bstarkey24@ebay.co.uk",
    gender: "Female",
    dependent: false,
    contributionAmount: 61,
    contributionMethod: "Bank Transfer",
    dateJoined: "2024-06-14T17:48:54Z",
  },
  {
    id: 78,
    first_name: "Laurens",
    last_name: "Chiles",
    email: "lchiles25@shop-pro.jp",
    gender: "Male",
    dependent: false,
    contributionAmount: 18,
    contributionMethod: "Check",
    dateJoined: "2024-03-04T10:28:45Z",
  },
  {
    id: 79,
    first_name: "Conni",
    last_name: "De Ferrari",
    email: "cdeferrari26@house.gov",
    gender: "Female",
    dependent: true,
    contributionAmount: 29,
    contributionMethod: "Credit Card",
    dateJoined: "2023-12-08T06:27:26Z",
  },
  {
    id: 80,
    first_name: "Glen",
    last_name: "Rhymes",
    email: "grhymes27@goo.ne.jp",
    gender: "Polygender",
    dependent: false,
    contributionAmount: 26,
    contributionMethod: "Cash",
    dateJoined: "2024-04-29T11:17:39Z",
  },
  {
    id: 81,
    first_name: "Marcile",
    last_name: "Georger",
    email: "mgeorger28@cpanel.net",
    gender: "Female",
    dependent: false,
    contributionAmount: 49,
    contributionMethod: "Credit Card",
    dateJoined: "2023-06-28T23:08:59Z",
  },
  {
    id: 82,
    first_name: "Derrek",
    last_name: "Mander",
    email: "dmander29@desdev.cn",
    gender: "Male",
    dependent: false,
    contributionAmount: 23,
    contributionMethod: "Cash",
    dateJoined: "2024-06-19T16:34:14Z",
  },
  {
    id: 83,
    first_name: "Nappy",
    last_name: "Eddie",
    email: "neddie2a@upenn.edu",
    gender: "Male",
    dependent: false,
    contributionAmount: 58,
    contributionMethod: "Online Payment",
    dateJoined: "2023-09-18T00:11:53Z",
  },
  {
    id: 84,
    first_name: "Taite",
    last_name: "Daines",
    email: "tdaines2b@jiathis.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 46,
    contributionMethod: "Check",
    dateJoined: "2024-04-17T19:30:21Z",
  },
  {
    id: 85,
    first_name: "Daven",
    last_name: "Farraway",
    email: "dfarraway2c@fotki.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 87,
    contributionMethod: "Check",
    dateJoined: "2023-12-10T09:56:48Z",
  },
  {
    id: 86,
    first_name: "Beverie",
    last_name: "Lamacraft",
    email: "blamacraft2d@gravatar.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 27,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-09-20T07:00:26Z",
  },
  {
    id: 87,
    first_name: "Lauraine",
    last_name: "Gheerhaert",
    email: "lgheerhaert2e@zimbio.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 60,
    contributionMethod: "Check",
    dateJoined: "2023-12-20T17:53:39Z",
  },
  {
    id: 88,
    first_name: "Floris",
    last_name: "Elloway",
    email: "felloway2f@amazon.co.jp",
    gender: "Female",
    dependent: false,
    contributionAmount: 30,
    contributionMethod: "Online Payment",
    dateJoined: "2024-05-01T07:06:27Z",
  },
  {
    id: 89,
    first_name: "Keslie",
    last_name: "Rylands",
    email: "krylands2g@ca.gov",
    gender: "Female",
    dependent: false,
    contributionAmount: 92,
    contributionMethod: "Credit Card",
    dateJoined: "2023-11-05T16:35:16Z",
  },
  {
    id: 90,
    first_name: "Joellyn",
    last_name: "Redgrave",
    email: "jredgrave2h@blogger.com",
    gender: "Female",
    dependent: false,
    contributionAmount: 87,
    contributionMethod: "Credit Card",
    dateJoined: "2024-05-16T01:16:19Z",
  },
  {
    id: 91,
    first_name: "Deerdre",
    last_name: "Mill",
    email: "dmill2i@tmall.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 65,
    contributionMethod: "Check",
    dateJoined: "2023-10-06T01:17:26Z",
  },
  {
    id: 92,
    first_name: "Merrill",
    last_name: "Lillistone",
    email: "mlillistone2j@webnode.com",
    gender: "Female",
    dependent: true,
    contributionAmount: 72,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-08-06T03:03:54Z",
  },
  {
    id: 93,
    first_name: "Winfield",
    last_name: "Mockler",
    email: "wmockler2k@youtu.be",
    gender: "Non-binary",
    dependent: false,
    contributionAmount: 62,
    contributionMethod: "Online Payment",
    dateJoined: "2023-08-17T20:28:49Z",
  },
  {
    id: 94,
    first_name: "Ingemar",
    last_name: "Purkins",
    email: "ipurkins2l@utexas.edu",
    gender: "Male",
    dependent: true,
    contributionAmount: 63,
    contributionMethod: "Online Payment",
    dateJoined: "2024-01-14T04:09:32Z",
  },
  {
    id: 95,
    first_name: "Maximilian",
    last_name: "Staniforth",
    email: "mstaniforth2m@blogs.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 50,
    contributionMethod: "Credit Card",
    dateJoined: "2024-05-04T06:42:26Z",
  },
  {
    id: 96,
    first_name: "Nicolis",
    last_name: "Poultney",
    email: "npoultney2n@geocities.jp",
    gender: "Male",
    dependent: false,
    contributionAmount: 58,
    contributionMethod: "Check",
    dateJoined: "2024-05-19T11:34:55Z",
  },
  {
    id: 97,
    first_name: "Stewart",
    last_name: "Rassell",
    email: "srassell2o@cnet.com",
    gender: "Male",
    dependent: false,
    contributionAmount: 97,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-07-17T14:45:40Z",
  },
  {
    id: 98,
    first_name: "Haily",
    last_name: "Dykins",
    email: "hdykins2p@github.com",
    gender: "Male",
    dependent: true,
    contributionAmount: 51,
    contributionMethod: "Credit Card",
    dateJoined: "2024-03-01T00:45:12Z",
  },
  {
    id: 99,
    first_name: "Kalil",
    last_name: "McAuslene",
    email: "kmcauslene2q@princeton.edu",
    gender: "Male",
    dependent: true,
    contributionAmount: 35,
    contributionMethod: "Cash",
    dateJoined: "2023-12-12T14:07:25Z",
  },
  {
    id: 100,
    first_name: "Elbertine",
    last_name: "Huckin",
    email: "ehuckin2r@gov.uk",
    gender: "Female",
    dependent: true,
    contributionAmount: 99,
    contributionMethod: "Bank Transfer",
    dateJoined: "2023-12-16T07:26:07Z",
  },
];
